/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq.tables;


import eu.dissco.annotationprocessingservice.database.jooq.Keys;
import eu.dissco.annotationprocessingservice.database.jooq.Public;
import eu.dissco.annotationprocessingservice.database.jooq.tables.records.AnnotationTmpRecord;

import java.time.Instant;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function18;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnnotationTmp extends TableImpl<AnnotationTmpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.annotation_tmp</code>
     */
    public static final AnnotationTmp ANNOTATION_TMP = new AnnotationTmp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnnotationTmpRecord> getRecordType() {
        return AnnotationTmpRecord.class;
    }

    /**
     * The column <code>public.annotation_tmp.id</code>.
     */
    public final TableField<AnnotationTmpRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.version</code>.
     */
    public final TableField<AnnotationTmpRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.type</code>.
     */
    public final TableField<AnnotationTmpRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.motivation</code>.
     */
    public final TableField<AnnotationTmpRecord, String> MOTIVATION = createField(DSL.name("motivation"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.motivated_by</code>.
     */
    public final TableField<AnnotationTmpRecord, String> MOTIVATED_BY = createField(DSL.name("motivated_by"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.annotation_tmp.target_id</code>.
     */
    public final TableField<AnnotationTmpRecord, String> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.target</code>.
     */
    public final TableField<AnnotationTmpRecord, JSONB> TARGET = createField(DSL.name("target"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.body</code>.
     */
    public final TableField<AnnotationTmpRecord, JSONB> BODY = createField(DSL.name("body"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.creator_id</code>.
     */
    public final TableField<AnnotationTmpRecord, String> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.creator</code>.
     */
    public final TableField<AnnotationTmpRecord, JSONB> CREATOR = createField(DSL.name("creator"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.created</code>.
     */
    public final TableField<AnnotationTmpRecord, Instant> CREATED = createField(DSL.name("created"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.generator</code>.
     */
    public final TableField<AnnotationTmpRecord, JSONB> GENERATOR = createField(DSL.name("generator"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.generated</code>.
     */
    public final TableField<AnnotationTmpRecord, Instant> GENERATED = createField(DSL.name("generated"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.last_checked</code>.
     */
    public final TableField<AnnotationTmpRecord, Instant> LAST_CHECKED = createField(DSL.name("last_checked"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.annotation_tmp.aggregate_rating</code>.
     */
    public final TableField<AnnotationTmpRecord, JSONB> AGGREGATE_RATING = createField(DSL.name("aggregate_rating"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.annotation_tmp.deleted_on</code>.
     */
    public final TableField<AnnotationTmpRecord, Instant> DELETED_ON = createField(DSL.name("deleted_on"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.annotation_tmp.annotation_hash</code>.
     */
    public final TableField<AnnotationTmpRecord, UUID> ANNOTATION_HASH = createField(DSL.name("annotation_hash"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.annotation_tmp.mjr_job_id</code>.
     */
    public final TableField<AnnotationTmpRecord, String> MJR_JOB_ID = createField(DSL.name("mjr_job_id"), SQLDataType.CLOB, this, "");

    private AnnotationTmp(Name alias, Table<AnnotationTmpRecord> aliased) {
        this(alias, aliased, null);
    }

    private AnnotationTmp(Name alias, Table<AnnotationTmpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.annotation_tmp</code> table reference
     */
    public AnnotationTmp(String alias) {
        this(DSL.name(alias), ANNOTATION_TMP);
    }

    /**
     * Create an aliased <code>public.annotation_tmp</code> table reference
     */
    public AnnotationTmp(Name alias) {
        this(alias, ANNOTATION_TMP);
    }

    /**
     * Create a <code>public.annotation_tmp</code> table reference
     */
    public AnnotationTmp() {
        this(DSL.name("annotation_tmp"), null);
    }

    public <O extends Record> AnnotationTmp(Table<O> child, ForeignKey<O, AnnotationTmpRecord> key) {
        super(child, key, ANNOTATION_TMP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AnnotationTmpRecord> getPrimaryKey() {
        return Keys.ANNOTATION_TMP_PK;
    }

    @Override
    public AnnotationTmp as(String alias) {
        return new AnnotationTmp(DSL.name(alias), this);
    }

    @Override
    public AnnotationTmp as(Name alias) {
        return new AnnotationTmp(alias, this);
    }

    @Override
    public AnnotationTmp as(Table<?> alias) {
        return new AnnotationTmp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationTmp rename(String name) {
        return new AnnotationTmp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationTmp rename(Name name) {
        return new AnnotationTmp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationTmp rename(Table<?> name) {
        return new AnnotationTmp(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<String, Integer, String, String, String, String, JSONB, JSONB, String, JSONB, Instant, JSONB, Instant, Instant, JSONB, Instant, UUID, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function18<? super String, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super JSONB, ? super JSONB, ? super String, ? super JSONB, ? super Instant, ? super JSONB, ? super Instant, ? super Instant, ? super JSONB, ? super Instant, ? super UUID, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function18<? super String, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super JSONB, ? super JSONB, ? super String, ? super JSONB, ? super Instant, ? super JSONB, ? super Instant, ? super Instant, ? super JSONB, ? super Instant, ? super UUID, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
