/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq.tables;


import eu.dissco.annotationprocessingservice.database.jooq.Keys;
import eu.dissco.annotationprocessingservice.database.jooq.Public;
import eu.dissco.annotationprocessingservice.database.jooq.tables.records.AnnotationBatchRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnnotationBatch extends TableImpl<AnnotationBatchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.annotation_batch</code>
     */
    public static final AnnotationBatch ANNOTATION_BATCH = new AnnotationBatch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnnotationBatchRecord> getRecordType() {
        return AnnotationBatchRecord.class;
    }

    /**
     * The column <code>public.annotation_batch.batch_id</code>.
     */
    public final TableField<AnnotationBatchRecord, UUID> BATCH_ID = createField(DSL.name("batch_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.annotation_batch.creator_user</code>.
     */
    public final TableField<AnnotationBatchRecord, String> CREATOR_USER = createField(DSL.name("creator_user"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_batch.creator_mas</code>.
     */
    public final TableField<AnnotationBatchRecord, String> CREATOR_MAS = createField(DSL.name("creator_mas"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.annotation_batch.parent_annotation_id</code>.
     */
    public final TableField<AnnotationBatchRecord, String> PARENT_ANNOTATION_ID = createField(DSL.name("parent_annotation_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.annotation_batch.created_on</code>.
     */
    public final TableField<AnnotationBatchRecord, Instant> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.annotation_batch.last_updated</code>.
     */
    public final TableField<AnnotationBatchRecord, Instant> LAST_UPDATED = createField(DSL.name("last_updated"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.annotation_batch.job_id</code>.
     */
    public final TableField<AnnotationBatchRecord, String> JOB_ID = createField(DSL.name("job_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.annotation_batch.batch_quantity</code>.
     */
    public final TableField<AnnotationBatchRecord, Long> BATCH_QUANTITY = createField(DSL.name("batch_quantity"), SQLDataType.BIGINT, this, "");

    private AnnotationBatch(Name alias, Table<AnnotationBatchRecord> aliased) {
        this(alias, aliased, null);
    }

    private AnnotationBatch(Name alias, Table<AnnotationBatchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.annotation_batch</code> table reference
     */
    public AnnotationBatch(String alias) {
        this(DSL.name(alias), ANNOTATION_BATCH);
    }

    /**
     * Create an aliased <code>public.annotation_batch</code> table reference
     */
    public AnnotationBatch(Name alias) {
        this(alias, ANNOTATION_BATCH);
    }

    /**
     * Create a <code>public.annotation_batch</code> table reference
     */
    public AnnotationBatch() {
        this(DSL.name("annotation_batch"), null);
    }

    public <O extends Record> AnnotationBatch(Table<O> child, ForeignKey<O, AnnotationBatchRecord> key) {
        super(child, key, ANNOTATION_BATCH);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AnnotationBatchRecord> getPrimaryKey() {
        return Keys.ANNOTATION_BATCH_PK;
    }

    @Override
    public List<ForeignKey<AnnotationBatchRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ANNOTATION_BATCH__ANNOTATION_BATCH_FK);
    }

    private transient MasJobRecord _masJobRecord;

    /**
     * Get the implicit join path to the <code>public.mas_job_record</code>
     * table.
     */
    public MasJobRecord masJobRecord() {
        if (_masJobRecord == null)
            _masJobRecord = new MasJobRecord(this, Keys.ANNOTATION_BATCH__ANNOTATION_BATCH_FK);

        return _masJobRecord;
    }

    @Override
    public AnnotationBatch as(String alias) {
        return new AnnotationBatch(DSL.name(alias), this);
    }

    @Override
    public AnnotationBatch as(Name alias) {
        return new AnnotationBatch(alias, this);
    }

    @Override
    public AnnotationBatch as(Table<?> alias) {
        return new AnnotationBatch(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationBatch rename(String name) {
        return new AnnotationBatch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationBatch rename(Name name) {
        return new AnnotationBatch(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationBatch rename(Table<?> name) {
        return new AnnotationBatch(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, String, Instant, Instant, String, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super UUID, ? super String, ? super String, ? super String, ? super Instant, ? super Instant, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super UUID, ? super String, ? super String, ? super String, ? super Instant, ? super Instant, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
