/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq;


import eu.dissco.annotationprocessingservice.database.jooq.tables.Annotation;
import eu.dissco.annotationprocessingservice.database.jooq.tables.DigitalSpecimen;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ANNOTATION_HASH_IDX = Internal.createIndex(DSL.name("annotation_hash_idx"), Annotation.ANNOTATION, new OrderField[] { Annotation.ANNOTATION.ANNOTATION_HASH }, false);
    public static final Index ANNOTATION_ID_CREATOR_ID_INDEX = Internal.createIndex(DSL.name("annotation_id_creator_id_index"), Annotation.ANNOTATION, new OrderField[] { Annotation.ANNOTATION.CREATOR }, false);
    public static final Index ANNOTATION_ID_TARGET_ID_INDEX = Internal.createIndex(DSL.name("annotation_id_target_id_index"), Annotation.ANNOTATION, new OrderField[] { Annotation.ANNOTATION.TARGET_ID }, false);
    public static final Index DIGITAL_SPECIMEN_CREATED_IDX = Internal.createIndex(DSL.name("digital_specimen_created_idx"), DigitalSpecimen.DIGITAL_SPECIMEN, new OrderField[] { DigitalSpecimen.DIGITAL_SPECIMEN.CREATED }, false);
    public static final Index DIGITAL_SPECIMEN_PHYSICAL_SPECIMEN_ID_IDX = Internal.createIndex(DSL.name("digital_specimen_physical_specimen_id_idx"), DigitalSpecimen.DIGITAL_SPECIMEN, new OrderField[] { DigitalSpecimen.DIGITAL_SPECIMEN.PHYSICAL_SPECIMEN_ID }, false);
}
