/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq;


import eu.dissco.annotationprocessingservice.database.jooq.tables.Annotation;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ANNOTATION_HASH = Internal.createIndex(DSL.name("annotation_hash"), Annotation.ANNOTATION, new OrderField[] { Annotation.ANNOTATION.ANNOTATION_HASH }, false);
    public static final Index ANNOTATION_ID_CREATOR_ID_INDEX = Internal.createIndex(DSL.name("annotation_id_creator_id_index"), Annotation.ANNOTATION, new OrderField[] { Annotation.ANNOTATION.CREATOR }, false);
    public static final Index ANNOTATION_ID_TARGET_ID_INDEX = Internal.createIndex(DSL.name("annotation_id_target_id_index"), Annotation.ANNOTATION, new OrderField[] { Annotation.ANNOTATION.TARGET_ID }, false);
}
