/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq;


import eu.dissco.annotationprocessingservice.database.jooq.tables.Annotation;
import eu.dissco.annotationprocessingservice.database.jooq.tables.AnnotationBatch;
import eu.dissco.annotationprocessingservice.database.jooq.tables.MasJobRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.annotation</code>.
     */
    public final Annotation ANNOTATION = Annotation.ANNOTATION;

    /**
     * The table <code>public.annotation_batch</code>.
     */
    public final AnnotationBatch ANNOTATION_BATCH = AnnotationBatch.ANNOTATION_BATCH;

    /**
     * The table <code>public.mas_job_record</code>.
     */
    public final MasJobRecord MAS_JOB_RECORD = MasJobRecord.MAS_JOB_RECORD;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Annotation.ANNOTATION,
            AnnotationBatch.ANNOTATION_BATCH,
            MasJobRecord.MAS_JOB_RECORD
        );
    }
}
