/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq;


import eu.dissco.annotationprocessingservice.database.jooq.tables.AnnotationTmp;
import eu.dissco.annotationprocessingservice.database.jooq.tables.MasJobRecordTmp;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.annotation_tmp</code>.
     */
    public static final AnnotationTmp ANNOTATION_TMP = AnnotationTmp.ANNOTATION_TMP;

    /**
     * The table <code>public.mas_job_record_tmp</code>.
     */
    public static final MasJobRecordTmp MAS_JOB_RECORD_TMP = MasJobRecordTmp.MAS_JOB_RECORD_TMP;
}
