/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq;


import eu.dissco.annotationprocessingservice.database.jooq.tables.AnnotationBatchRecord;
import eu.dissco.annotationprocessingservice.database.jooq.tables.MasJobRecord;
import eu.dissco.annotationprocessingservice.database.jooq.tables.NewAnnotation;
import eu.dissco.annotationprocessingservice.database.jooq.tables.SourceSystem;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.annotation_batch_record</code>.
     */
    public static final AnnotationBatchRecord ANNOTATION_BATCH_RECORD = AnnotationBatchRecord.ANNOTATION_BATCH_RECORD;

    /**
     * The table <code>public.mas_job_record</code>.
     */
    public static final MasJobRecord MAS_JOB_RECORD = MasJobRecord.MAS_JOB_RECORD;

    /**
     * The table <code>public.new_annotation</code>.
     */
    public static final NewAnnotation NEW_ANNOTATION = NewAnnotation.NEW_ANNOTATION;

    /**
     * The table <code>public.source_system</code>.
     */
    public static final SourceSystem SOURCE_SYSTEM = SourceSystem.SOURCE_SYSTEM;
}
