/*
 * This file is generated by jOOQ.
 */
package eu.dissco.annotationprocessingservice.database.jooq;


import eu.dissco.annotationprocessingservice.database.jooq.tables.Annotation;
import eu.dissco.annotationprocessingservice.database.jooq.tables.MasJobRecord;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.annotation</code>.
     */
    public static final Annotation ANNOTATION = Annotation.ANNOTATION;

    /**
     * The table <code>public.mas_job_record</code>.
     */
    public static final MasJobRecord MAS_JOB_RECORD = MasJobRecord.MAS_JOB_RECORD;
}
